### ISSUE TITLE
tabulizer package won't install

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/wc18-age#1]
# Problem

Can't install `tabulizer`. Java installation issue.

# Solution

Follow advice:

* https://github.com/ropensci/tabulizer
* https://stackoverflow.com/questions/39132202/trouble-installing-tabulizer-package
* https://github.com/ropensci/tabulizer/issues/71
* https://gist.github.com/tomsing1/1da54d3f720ed96fbbb5a3f075bd2a56
* https://stackoverflow.com/questions/39132202/trouble-installing-tabulizer-package
* https://stackoverflow.com/questions/44346656/error-in-installing-tabulizer
* https://ropensci.org/tutorials/tabulizer_tutorial/

And probably more

**Comment by matt-dray** [comment]
Used an alternative data source: https://github.com/AllezCannes/WorldCupSquads

**Comment by lnalborczyk** [comment]
Still does not work on my machine. It gives the following error:

internal error -3 in R_decompress1Error: package or namespace load failed for ‘tabulizerjars’ in runHook(".onLoad", env, package.lib, package):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tabulizerjars/R/tabulizerjars.rdb' is corrupt

Any idea ?

**Comment by matt-dray** [comment]
Sorry @lnalborczyk, I don't have an answer. I found an alternative source of data for my project, which meant I didn't need to use `tabulizer` and so I didn't try any of the solutions linked in this issue.
